id: P000456
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:40:53.225711
source_metadata:
  id: bdr:W28811
  title: གཞི་ལམ་འབྲས་བུའི་སྨོན་ལམ་གྱི་དོན་གསལ་བར་བྱེད་པ་ཀུན་ཏུ་བཟང་པོའི་ཞལ་ལུང་།
  author: ''
  volumes:
    1c6564a424294c4097fd2f42bba1bad0:
      image_group_id: I4646
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
